### ISSUE TITLE
Data not found for common chemcials

### ISSUE THREAD

**Issue by shraddha2191** [httk/httk#29]
Hello everyone,
Recently I have tried HTTK to analyze some of my chemicals. While preforming calc_analytic_css, calc_css, calc_elimination_rate, calc_elimination_rate,  parameterize_steadystate etc paramters. for certain common chemicals like Phenol, Acetaldehyde, Acetophenone, Acrolein, Acrylonitrile, Benzaldehyde, the result obtained says  physiology.data not found or chem.physical_and_invitro.data' not found. I have used the CAS no. for this analysis. I would like to confirm is it the knowledge gap or I m missing any steps in the analysis?

Kindly resolve my query

**Comment by rartino** [comment]
Hi @shraddha2191,

Are you perhaps looking for the R package "High-Throughput Toxicokinetics" which unfortunately also has chosen to abbreviate themselves as httk? I think their github page is here:
- https://github.com/USEPA/CompTox-ExpoCast-httk

(The high-throughput toolkit has been open source since 2013, whereas it seems the first release of the R package was in 2015, so it is unfortunate that they chose a name already in use.)

**Comment by rartino** [comment]
I'm going to go ahead and close this, since it does not appear to be related to this software package.
